import type { Metadata } from "next";
import "./globals.css";
import { libreFranklin } from "@/assets/fonts";
import VanishingButton from "@/components/client/VanishingButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${libreFranklin.className} antialiased bg-white relative min-h-[100vh]`}
      >
        {children}
        <VanishingButton />
      </body>
    </html>
  );
}
